# -*- coding: utf-8 -*-
"""python_day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mm2-uC5MsY5D3QayaAx57XaYai_iGx3W
"""



"""#**Module 2: Python Syntax & Basics**"""

# ============================================================
# 1. PYTHON SYNTAX
# ============================================================

# Example 1
print("Hello World")

# Example 2
print("Welcome to C-DAC")

# Example 3
print(100)

# Example 4
print(3.14)

# Example 5
print(10 + 20)

# Example 6
if True:
    print("Indentation Example")

# Example 7
# Single-line comment
print("Comments")

# Example 8
"""
Multi-line comment
"""
print("Syntax Complete")

# ============================================================
# VARIABLES
# ============================================================

# A variable is used to store data in memory.
# Python automatically determines the data type.

name = "Himanshu"

print(name)


# Variables can store numbers.

age = 24

print(age)


# Variables can store decimal values.

cgpa = 8.75

print(cgpa)


# Variables can store True or False values.

is_placed = True

print(is_placed)


# Updating a variable.

city = "Mohali"

print(city)

city = "Chandigarh"

print(city)


# Multiple variables.

course = "Python"
duration = 6
fee = 5000

print(course)
print(duration)
print(fee)


# Multiple assignment.

x, y, z = 10, 20, 30

print(x)
print(y)
print(z)


# Same value assigned to multiple variables.

a = b = c = 100

print(a)
print(b)
print(c)


# Student record example.

student_name = "Rahul"
student_marks = 92
student_branch = "CSE"

print(student_name)
print(student_marks)
print(student_branch)


# Banking example.

account_holder = "Aman"
account_balance = 25000

print(account_holder)
print(account_balance)


# E-commerce example.

product_name = "Laptop"
product_price = 65000

print(product_name)
print(product_price)


# Healthcare example.

patient_name = "Riya"
patient_age = 32

print(patient_name)
print(patient_age)


# AI example.

model_name = "Random Forest"
accuracy = 96.5

print(model_name)
print(accuracy)


# Checking variable types.

salary = 45000

print(type(salary))

name = "Rahul"

print(type(name))

cgpa = 8.9

print(type(cgpa))


# Variables are case-sensitive.

student = "Aman"
Student = "Rahul"

print(student)
print(Student)


# Simple practice.

college = "Chandigarh University"
semester = 8

print(college)
print(semester)

# ============================================================
# NAMING CONVENTIONS
# ============================================================

# Naming conventions make code easier to read and maintain.

# Use meaningful variable names.

student_name = "Rahul"
student_marks = 95

print(student_name)
print(student_marks)


# Avoid unclear variable names.

x = 95

print(x)

# Better approach.

exam_marks = 95

print(exam_marks)


# Python commonly uses snake_case.

employee_name = "Aman"
employee_salary = 50000

print(employee_name)
print(employee_salary)


# Banking example.

account_holder = "Rohit"
account_balance = 75000

print(account_holder)
print(account_balance)


# E-commerce example.

product_name = "Smartphone"
product_price = 25000

print(product_name)
print(product_price)


# Healthcare example.

patient_name = "Riya"
blood_group = "O+"

print(patient_name)
print(blood_group)


# Weather application example.

city_name = "Mohali"
temperature_celsius = 36

print(city_name)
print(temperature_celsius)


# AI and Machine Learning example.

training_accuracy = 98.2
model_version = "v1.0"

print(training_accuracy)
print(model_version)


# Variable names may contain numbers.

student1 = "Aman"
student2 = "Rahul"

print(student1)
print(student2)


# Variable names may begin with an underscore.

_internal_value = 100

print(_internal_value)


# Case sensitivity.

course_name = "Python"
Course_Name = "Machine Learning"

print(course_name)
print(Course_Name)


# Invalid examples.
# Uncommenting these lines will produce errors.

# 1student = "Aman"
# student-name = "Rahul"
# student name = "Rahul"


# Comparing poor and meaningful naming.

a = 45000
b = 5000

print(a - b)

monthly_salary = 45000
monthly_expense = 5000

print(monthly_salary - monthly_expense)


# Real-world project style naming.

customer_id = 101
customer_name = "Ravi"
order_amount = 1499

print(customer_id)
print(customer_name)
print(order_amount)


# Practice activity.

college_name = "Chandigarh University"
course_name = "Computer Science"
graduation_year = 2025

print(college_name)
print(course_name)
print(graduation_year)

# ============================================================
# KEYWORDS
# ============================================================

# Keywords are reserved words in Python.
# They have predefined meanings and cannot be used as variable names.

import keyword

# Display all Python keywords.

print(keyword.kwlist)


# Total number of keywords.

print("Total Keywords:", len(keyword.kwlist))


# Display first 10 keywords.

for word in keyword.kwlist[:10]:
    print(word)


# Using the 'if' keyword.

age = 20

if age >= 18:
    print("Eligible to vote")


# Using the 'else' keyword.

marks = 45

if marks >= 40:
    print("Pass")
else:
    print("Fail")


# Using the 'for' keyword.

for i in range(5):
    print(i)


# Using the 'while' keyword.

count = 1

while count <= 3:
    print(count)
    count += 1


# Using the 'True' and 'False' keywords.

is_logged_in = True

print(is_logged_in)

print(False)


# Using the 'and' keyword.

username_valid = True
password_valid = True

if username_valid and password_valid:
    print("Login Successful")


# Using the 'or' keyword.

mobile_verified = False
email_verified = True

if mobile_verified or email_verified:
    print("Account Verified")


# Using the 'not' keyword.

is_blocked = False

if not is_blocked:
    print("Access Granted")


# Keywords cannot be used as variable names.

# class = "Python"
# if = 10
# for = 20

# These statements will generate SyntaxError.


# Correct alternatives.

class_name = "Python"

print(class_name)


# Check whether a word is a keyword.

print("for" in keyword.kwlist)

print("student" in keyword.kwlist)


# Real-world example.

transaction_status = True

if transaction_status:
    print("Transaction Successful")


# Mini practice.

for number in range(1, 6):
    print("Roll Number:", number)

# ============================================================
# IDENTIFIERS
# ============================================================

# Identifiers are names given to variables, functions,
# classes and other objects in Python.

# Valid identifier.

student_name = "Rahul"

print(student_name)


# Identifiers can contain letters and numbers.

student1 = "Aman"

print(student1)


# Identifiers can start with an underscore.

_employee_id = 101

print(_employee_id)


# Identifiers are case-sensitive.

name = "Rahul"
Name = "Aman"

print(name)
print(Name)


# Banking example.

account_holder = "Rohit"
account_balance = 50000

print(account_holder)
print(account_balance)


# E-commerce example.

product_name = "Laptop"
product_price = 65000

print(product_name)
print(product_price)


# Healthcare example.

patient_name = "Riya"
patient_age = 30

print(patient_name)
print(patient_age)


# AI example.

model_name = "Random Forest"
training_accuracy = 97.5

print(model_name)
print(training_accuracy)


# Weather application example.

city_name = "Mohali"
temperature_value = 35

print(city_name)
print(temperature_value)


# Education example.

course_name = "Python"
course_duration = 6

print(course_name)
print(course_duration)


# Function name as identifier.

def greet_student():
    print("Welcome to C-DAC Mohali")

greet_student()


# Class name as identifier.

class Student:
    pass

print("Student class created")


# Invalid identifiers.

# 1student = "Rahul"
# student-name = "Rahul"
# student name = "Rahul"

# These will generate SyntaxError.


# Compare valid and invalid naming styles.

student_marks = 95

print(student_marks)

# student-marks = 95  # Invalid


# Real-world project naming.

customer_id = 1001
customer_name = "Amit"
order_amount = 2499

print(customer_id)
print(customer_name)
print(order_amount)


# Checking type of identifiers.

salary = 50000

print(type(salary))

employee_name = "Ankit"

print(type(employee_name))


# Practice section.

college_name = "Chandigarh University"
department_name = "Computer Science"

print(college_name)
print(department_name)

# ============================================================
# CONSTANTS
# ============================================================

# Python does not have built-in constants.
# By convention, constants are written in uppercase.

PI = 3.14159

print(PI)


# Mathematical constants.

GRAVITY = 9.8

print(GRAVITY)


# Banking application.

MINIMUM_BALANCE = 1000

print(MINIMUM_BALANCE)


# E-commerce application.

GST_RATE = 18

print(GST_RATE)


# Education system.

MAX_MARKS = 100

print(MAX_MARKS)


# Healthcare application.

NORMAL_BODY_TEMPERATURE = 98.6

print(NORMAL_BODY_TEMPERATURE)


# AI application.

LEARNING_RATE = 0.01

print(LEARNING_RATE)


# Constants can still be modified, but it is not recommended.

COMPANY_NAME = "C-DAC"

print(COMPANY_NAME)


# Practice example.

COLLEGE_NAME = "Chandigarh University"

print(COLLEGE_NAME)

# ============================================================
# INPUT AND OUTPUT
# ============================================================

# Output using print().

print("Welcome to Python")


# Output text and numbers.

print("Age:", 24)

print("Marks:", 95)


# Output multiple values.

name = "Rahul"
course = "Python"

print(name, course)


# Student information.

student_name = "Aman"
student_marks = 92

print(student_name)
print(student_marks)


# Banking example.

account_holder = "Rohit"
account_balance = 25000

print(account_holder)
print(account_balance)


# E-commerce example.

product_name = "Laptop"
product_price = 65000

print(product_name)
print(product_price)


# Healthcare example.

patient_name = "Riya"

print(patient_name)


# AI example.

model_name = "Random Forest"

print(model_name)

# ============================================================
# PRINT FUNCTION
# ============================================================

# Printing text.

print("Hello World")


# Printing numbers.

print(100)

print(3.14)


# Printing multiple values.

name = "Rahul"
age = 24

print(name, age)


# Using separator.

print("Python", "AI", "ML", sep=" | ")


# Using end parameter.

print("Hello", end=" ")
print("World")


# Formatted string.

student_name = "Aman"
marks = 95

print(f"{student_name} scored {marks} marks")


# format() method.

print("My age is {}".format(24))


# Banking example.

account_holder = "Rohit"
balance = 50000

print(f"Account Holder: {account_holder}")
print(f"Balance: {balance}")


# E-commerce example.

product = "Laptop"
price = 65000

print(f"Product: {product}")
print(f"Price: {price}")


# AI example.

model = "CNN"
accuracy = 97.5

print(f"Model: {model}")
print(f"Accuracy: {accuracy}%")

# ============================================================
# USER INPUT
# ============================================================

# Uncomment while teaching in class.

 name = input("Enter your name: ")
 print(name)


 age = input("Enter your age: ")
 print(age)


 city = input("Enter your city: ")
 print(city)


 Student information.

 student_name = input("Enter student name: ")
 print(student_name)


 Banking example.

# account_holder = input("Enter account holder name: ")
# print(account_holder)


# E-commerce example.

product_name = input("Enter product name: ")
print(product_name)


# Healthcare example.

# patient_name = input("Enter patient name: ")
# print(patient_name)


# AI example.

# model_name = input("Enter model name: ")
# print(model_name)


# Multiple inputs.

# name = input("Enter name: ")
# course = input("Enter course: ")

# print(name)
# print(course)

# ============================================================
# ESCAPE CHARACTERS
# ============================================================

# New line.

print("Welcome\nTo\nPython")


# Tab space.

print("Python\tProgramming")


# Single quote.

print('It\'s a Python Workshop')


# Double quote.

print("He said \"Hello\"")


# Backslash.

print("C:\\Users\\Student")


# Multiple lines.

print("Name\tMarks")
print("Rahul\t95")
print("Aman\t92")


# Banking example.

print("Account Holder:\tRohit")
print("Balance:\t50000")


# E-commerce example.

print("Product:\tLaptop")
print("Price:\t\t65000")

# ============================================================
# TYPE CONVERSION
# ============================================================

# String to integer.

num = "100"

converted_num = int(num)

print(converted_num)
print(type(converted_num))


# String to float.

price = "599.99"

converted_price = float(price)

print(converted_price)
print(type(converted_price))


# Integer to string.

marks = 95

marks_text = str(marks)

print(marks_text)
print(type(marks_text))


# Integer to float.

salary = 50000

salary_float = float(salary)

print(salary_float)


# Float to integer.

cgpa = 8.75

cgpa_int = int(cgpa)

print(cgpa_int)


# Boolean conversion.

print(bool(1))
print(bool(0))


# Banking example.

balance = "25000"

balance = int(balance)

print(balance)


# E-commerce example.

price = "65000"

price = int(price)

print(price)


# AI example.

accuracy = "97.5"

accuracy = float(accuracy)

print(accuracy)

# ============================================================
# TYPE CASTING
# ============================================================

# Explicit type casting.

age = 24

age_float = float(age)

print(age_float)


# Float to integer.

salary = 45000.75

salary_int = int(salary)

print(salary_int)


# Integer to string.

roll_no = 101

roll_text = str(roll_no)

print(roll_text)


# String to integer.

marks = "95"

marks_int = int(marks)

print(marks_int)


# String to float.

cgpa = "8.75"

cgpa_float = float(cgpa)

print(cgpa_float)


# Boolean casting.

print(bool(100))
print(bool(0))


# Banking example.

balance = "50000"

balance_int = int(balance)

print(balance_int)


# E-commerce example.

product_price = "79999"

product_price_int = int(product_price)

print(product_price_int)


# Healthcare example.

patient_age = "35"

patient_age_int = int(patient_age)

print(patient_age_int)


# AI example.

accuracy = "98.6"

accuracy_float = float(accuracy)

print(accuracy_float)

"""#**Module 3: Data Types**"""

# ============================================================
# INTEGER
# ============================================================

# Integer values are whole numbers without decimal points.

age = 24
print(age)
print(type(age))

marks = 95
print(marks)
print(type(marks))

temperature = -5
print(temperature)
print(type(temperature))

population = 1400000000
print(population)
print(type(population))

# ============================================================
# FLOAT
# ============================================================

# Float values contain decimal points.

cgpa = 8.75
print(cgpa)
print(type(cgpa))

price = 599.99
print(price)
print(type(price))

temperature = 36.5
print(temperature)
print(type(temperature))

accuracy = 98.76
print(accuracy)
print(type(accuracy))

# ============================================================
# COMPLEX
# ============================================================

# Complex numbers contain a real and imaginary part.

num1 = 2 + 3j
print(num1)
print(type(num1))

num2 = 5 - 2j
print(num2)
print(type(num2))

num3 = complex(10, 4)
print(num3)
print(type(num3))

num4 = 7 + 0j
print(num4)
print(type(num4))

# ============================================================
# BOOLEAN
# ============================================================

# Boolean values can be either True or False.

is_logged_in = True
print(is_logged_in)
print(type(is_logged_in))

is_admin = False
print(is_admin)
print(type(is_admin))

print(10 > 5)
print(type(10 > 5))

print(20 < 10)
print(type(20 < 10))

# ============================================================
# STRING
# ============================================================

# Strings are sequences of characters enclosed in quotes.

name = "Himanshu"
print(name)
print(type(name))

course = 'Python'
print(course)
print(type(course))

college = "Chandigarh University"
print(college)
print(type(college))

message = "Welcome to C-DAC Mohali"
print(message)
print(type(message))

# ============================================================
# NONE TYPE
# ============================================================

# None represents the absence of a value.

result = None
print(result)
print(type(result))

student_data = None
print(student_data)
print(type(student_data))

response = None
print(response)
print(type(response))

model_prediction = None
print(model_prediction)
print(type(model_prediction))

"""#**Module 4: Operators**"""

# ============================================================
# ARITHMETIC OPERATORS
# ============================================================

# Arithmetic operators are used to perform mathematical operations.

a = 20
b = 5

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


# Floor Division

print("Floor Division:", a // b)


# Modulus

print("Remainder:", a % b)


# Exponentiation

print("Power:", a ** b)


# Student Example

total_marks = 450
subjects = 5

average = total_marks / subjects

print("Average Marks:", average)


# Shopping Example

price = 999
quantity = 3

bill = price * quantity

print("Total Bill:", bill)

# ============================================================
# ASSIGNMENT OPERATORS
# ============================================================

# Assignment operator

x = 10
print(x)


# +=

x += 5
print(x)


# -=

x -= 3
print(x)


# *=

x *= 2
print(x)


# /=

x /= 4
print(x)


# %=

x %= 3
print(x)


# **=

y = 2
y **= 3

print(y)


# Banking Example

balance = 10000

balance += 5000

print("Updated Balance:", balance)

# ============================================================
# COMPARISON OPERATORS
# ============================================================

# Comparison operators return True or False.

a = 20
b = 15

print(a == b)
print(a != b)

print(a > b)
print(a < b)

print(a >= b)
print(a <= b)


# Student Example

marks = 75

print(marks >= 40)


# Banking Example

balance = 5000

print(balance > 1000)

# ============================================================
# LOGICAL OPERATORS
# ============================================================

# and operator

username_valid = True
password_valid = True

print(username_valid and password_valid)


# or operator

mobile_verified = False
email_verified = True

print(mobile_verified or email_verified)


# not operator

is_blocked = False

print(not is_blocked)


# Student Example

attendance = True
fees_paid = True

print(attendance and fees_paid)


# Banking Example

aadhaar_verified = True
pan_verified = False

print(aadhaar_verified or pan_verified)


# AI Example

data_available = True
model_trained = True

print(data_available and model_trained)

# ============================================================
# BITWISE OPERATORS
# ============================================================

a = 10
b = 4

# AND

print(a & b)


# OR

print(a | b)


# XOR

print(a ^ b)


# NOT

print(~a)


# Left Shift

print(a << 1)


# Right Shift

print(a >> 1)


# Example

num = 8

print(num << 2)
print(num >> 2)

# ============================================================
# MEMBERSHIP OPERATORS
# ============================================================

# in operator

course = "Python"

print("P" in course)

print("Java" in course)


# not in operator

print("C" not in course)


# List Example

subjects = ["Python", "AI", "ML", "DL"]

print("AI" in subjects)

print("Java" in subjects)


# Student Example

students = ["Rahul", "Aman", "Riya"]

print("Rahul" in students)

print("Rohit" not in students)


# Shopping Example

cart_items = ["Laptop", "Mouse", "Keyboard"]

print("Laptop" in cart_items)

# ============================================================
# IDENTITY OPERATORS
# ============================================================

# Identity operators compare memory locations.

a = [1, 2, 3]
b = a

print(a is b)

print(a is not b)


# Different Objects

x = [1, 2, 3]
y = [1, 2, 3]

print(x is y)

print(x == y)


# Student Example

student1 = student2 = "Rahul"

print(student1 is student2)


# Integer Example

num1 = 100
num2 = 100

print(num1 is num2)

# ============================================================
# OPERATOR PRECEDENCE
# ============================================================

# Multiplication before addition

result = 10 + 5 * 2

print(result)


# Parentheses change precedence

result = (10 + 5) * 2

print(result)


# Multiple operators

result = 20 - 5 + 3 * 2

print(result)


# Division and Multiplication

result = 100 / 5 * 2

print(result)


# Exponentiation

result = 2 + 3 ** 2

print(result)


# Student Example

marks = 80 + 10 * 2

print(marks)


# Banking Example

amount = 10000 + 5000 * 2

print(amount)


# Complex Expression

result = (10 + 5) * 2 - 8 / 4

print(result)

# ============================================================
# OPERATOR PRECEDENCE
# ============================================================

# Multiplication before addition

result = 10 + 5 * 2

print(result)


# Parentheses change precedence

result = (10 + 5) * 2

print(result)


# Multiple operators

result = 20 - 5 + 3 * 2

print(result)


# Division and Multiplication

result = 100 / 5 * 2

print(result)


# Exponentiation

result = 2 + 3 ** 2

print(result)


# Student Example

marks = 80 + 10 * 2

print(marks)


# Banking Example

amount = 10000 + 5000 * 2

print(amount)


# Complex Expression

result = (10 + 5) * 2 - 8 / 4

print(result)

"""#**Module 5: Conditional Statements**"""

# ============================================================
# MODULE 5 : CONDITIONAL STATEMENTS
# ============================================================


# ============================================================
# IF STATEMENT
# ============================================================

age = 20

if age >= 18:
    print("Eligible to Vote")


marks = 85

if marks >= 40:
    print("Pass")


salary = 50000

if salary > 30000:
    print("Loan Eligible")


# ============================================================
# IF ELSE STATEMENT
# ============================================================

age = 16

if age >= 18:
    print("Eligible")
else:
    print("Not Eligible")


marks = 35

if marks >= 40:
    print("Pass")
else:
    print("Fail")


balance = 500

if balance >= 1000:
    print("Transaction Allowed")
else:
    print("Insufficient Balance")


# ============================================================
# IF ELIF ELSE LADDER
# ============================================================

marks = 82

if marks >= 90:
    print("Grade A+")
elif marks >= 75:
    print("Grade A")
elif marks >= 60:
    print("Grade B")
elif marks >= 40:
    print("Grade C")
else:
    print("Fail")


temperature = 28

if temperature > 40:
    print("Very Hot")
elif temperature > 30:
    print("Hot")
elif temperature > 20:
    print("Pleasant")
else:
    print("Cold")


# ============================================================
# NESTED IF
# ============================================================

age = 25
citizenship = "Indian"

if age >= 18:
    if citizenship == "Indian":
        print("Eligible to Vote")
    else:
        print("Citizenship Required")
else:
    print("Under Age")


# ============================================================
# SHORT HAND IF
# ============================================================

age = 20

if age >= 18: print("Eligible")


marks = 95

if marks >= 90: print("Excellent")


# ============================================================
# TERNARY OPERATOR
# ============================================================

age = 22

result = "Eligible" if age >= 18 else "Not Eligible"

print(result)


number = 7

result = "Even" if number % 2 == 0 else "Odd"

print(result)


# ============================================================
# MATCH CASE
# ============================================================

day = 3

match day:

    case 1:
        print("Monday")

    case 2:
        print("Tuesday")

    case 3:
        print("Wednesday")

    case _:
        print("Invalid Day")


role = "admin"

match role:

    case "admin":
        print("Full Access")

    case "user":
        print("Limited Access")

    case _:
        print("Unknown Role")


# ============================================================
# PRACTICE QUESTIONS
# ============================================================

# Question 1
# Check whether a number is positive or negative.

number = 10

if number >= 0:
    print("Positive")
else:
    print("Negative")


# Question 2
# Find largest among two numbers.

a = 20
b = 30

if a > b:
    print(a)
else:
    print(b)


# Question 3
# Check whether a student passed.

marks = 45

if marks >= 40:
    print("Pass")
else:
    print("Fail")