# -*- coding: utf-8 -*-
"""python_day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGEEgKBwMQrKikIyyIE8CrJjbH_cQK7s

#**Module 6: Loops**
"""

# ============================================================
# MODULE 6 : LOOPS
# ============================================================

# Loops are used to execute a block of code repeatedly.


# ============================================================
# WHILE LOOP
# ============================================================

# Print numbers from 1 to 5

count = 1

while count <= 5:
    print(count)
    count += 1


# Print even numbers from 2 to 10

number = 2

while number <= 10:
    print(number)
    number += 2


# Countdown Timer

timer = 5

while timer > 0:
    print(timer)
    timer -= 1

print("Time Up")


# Banking Example

balance = 1000

while balance <= 5000:
    print("Balance:", balance)
    balance += 1000


# Student Attendance Example

attendance_days = 1

while attendance_days <= 5:
    print("Day", attendance_days)
    attendance_days += 1


# ============================================================
# FOR LOOP
# ============================================================

# Print numbers from 0 to 4

for i in range(5):
    print(i)


# Print numbers from 1 to 5

for i in range(1, 6):
    print(i)


# Iterate through a string

for character in "Python":
    print(character)


# Iterate through a list

subjects = ["Python", "AI", "ML"]

for subject in subjects:
    print(subject)


# Student Names

students = ["Rahul", "Aman", "Riya"]

for student in students:
    print(student)


# Shopping Cart Example

cart_items = ["Laptop", "Mouse", "Keyboard"]

for item in cart_items:
    print(item)


# ============================================================
# NESTED LOOPS
# ============================================================

# Number Pattern

for i in range(3):
    for j in range(3):
        print(i, j)


# Star Pattern

for row in range(3):
    for col in range(3):
        print("*", end=" ")
    print()


# Multiplication Table Pattern

for i in range(1, 4):
    for j in range(1, 4):
        print(i * j, end=" ")
    print()


# Classroom Example

for classroom in range(1, 4):
    for student in range(1, 4):
        print("Class", classroom, "Student", student)


# ============================================================
# INFINITE LOOPS
# ============================================================

# Infinite loops continue forever until stopped manually.

# Example 1

# while True:
#     print("Running...")


# Example 2

# count = 1
#
# while count > 0:
#     print(count)


# Example 3

# for i in iter(int, 1):
#     print(i)


# Note:
# Infinite loops are commonly used in servers,
# games, chat applications and monitoring systems.


# ============================================================
# BREAK STATEMENT
# ============================================================

# break exits the loop immediately.

for i in range(10):

    if i == 5:
        break

    print(i)


# Student Example

students = ["Rahul", "Aman", "Riya", "Rohit"]

for student in students:

    if student == "Riya":
        break

    print(student)


# Banking Example

transactions = [1000, 2000, -5000, 3000]

for amount in transactions:

    if amount < 0:
        print("Suspicious Transaction Found")
        break

    print(amount)


# ============================================================
# CONTINUE STATEMENT
# ============================================================

# continue skips the current iteration.

for i in range(10):

    if i == 5:
        continue

    print(i)


# Print Odd Numbers

for number in range(1, 11):

    if number % 2 == 0:
        continue

    print(number)


# Student Example

marks = [90, 35, 85, 20, 78]

for mark in marks:

    if mark < 40:
        continue

    print(mark)


# ============================================================
# PASS STATEMENT
# ============================================================

# pass is a placeholder statement.

for i in range(5):

    if i == 3:
        pass

    print(i)


# Empty Function

def future_feature():
    pass


# Empty Class

class Student:
    pass


print("Program Continues")


# ============================================================
# RANGE FUNCTION
# ============================================================

# range(stop)

for i in range(5):
    print(i)


# range(start, stop)

for i in range(1, 6):
    print(i)


# range(start, stop, step)

for i in range(1, 11, 2):
    print(i)


# Reverse Counting

for i in range(10, 0, -1):
    print(i)


# Multiplication Table

for i in range(1, 11):
    print("5 x", i, "=", 5 * i)


# Year Example

for year in range(2020, 2026):
    print(year)


# ============================================================
# ENUMERATE FUNCTION
# ============================================================

# enumerate() provides both index and value.

subjects = ["Python", "AI", "ML"]

for index, subject in enumerate(subjects):
    print(index, subject)


# Starting index from 1

students = ["Rahul", "Aman", "Riya"]

for roll_no, student in enumerate(students, start=1):
    print(roll_no, student)


# Shopping Example

products = ["Laptop", "Mouse", "Keyboard"]

for item_no, product in enumerate(products, start=101):
    print(item_no, product)


# City Example

cities = ["Mohali", "Chandigarh", "Delhi"]

for index, city in enumerate(cities):
    print(index, city)


# AI Example

models = ["Linear Regression", "Random Forest", "CNN"]

for model_no, model in enumerate(models, start=1):
    print(model_no, model)


# ============================================================
# PRACTICE QUESTIONS
# ============================================================

# Question 1
# Print numbers from 1 to 20 using a while loop.


# Question 2
# Print all even numbers from 1 to 50.


# Question 3
# Print the multiplication table of 7.


# Question 4
# Print a 5 x 5 star pattern using nested loops.


# Question 5
# Print student names with roll numbers using enumerate().


# Question 6
# Use break to stop when number 8 is found.


# Question 7
# Use continue to skip all multiples of 3.


# Question 8
# Create a countdown from 10 to 1 using a while loop.


# Question 9
# Print all characters of your name using a for loop.


# Question 10
# Print all odd numbers between 1 and 100.

"""#**Module 7: Strings**"""

# ============================================================
# MODULE 7 : STRINGS
# ============================================================

# Strings are sequences of characters enclosed within
# single quotes, double quotes, or triple quotes.


# ============================================================
# STRING BASICS
# ============================================================

name = "Himanshu"
print(name)

course = 'Python Programming'
print(course)

message = """Welcome to
C-DAC Mohali"""
print(message)

city = "Mohali"
print(type(city))

# Student Example

student_name = "Rahul"
print(student_name)

# Banking Example

account_holder = "Aman"
print(account_holder)

# E-Commerce Example

product_name = "Laptop"
print(product_name)

# AI Example

model_name = "Random Forest"
print(model_name)


# ============================================================
# STRING INDEXING
# ============================================================

language = "Python"

print(language[0])
print(language[1])
print(language[2])

# Last Character

print(language[-1])

# Second Last Character

print(language[-2])

# Student Name Example

student = "Rahul"

print(student[0])
print(student[-1])

# Product Example

product = "Keyboard"

print(product[3])


# ============================================================
# STRING SLICING
# ============================================================

language = "Python Programming"

print(language[0:6])

print(language[7:18])

print(language[:6])

print(language[7:])

print(language[-11:])

print(language[::2])

print(language[::-1])

# Student Example

student_name = "Chandigarh"

print(student_name[0:5])


# ============================================================
# STRING METHODS
# ============================================================

text = "python programming"

print(text.upper())

print(text.lower())

print(text.title())

print(text.capitalize())

print(len(text))

# Remove Spaces

name = "   Rahul   "

print(name.strip())

# Replace

sentence = "I like Java"

print(sentence.replace("Java", "Python"))

# Split

courses = "Python,AI,ML,DL"

print(courses.split(","))

# Count

message = "Python Python AI Python"

print(message.count("Python"))

# Find

print(message.find("AI"))

# Startswith

print(message.startswith("Python"))

# Endswith

print(message.endswith("Python"))


# ============================================================
# STRING FORMATTING
# ============================================================

name = "Rahul"
age = 22

print("My name is {} and age is {}".format(name, age))

course = "Python"
duration = 6

print("Course: {} Duration: {} Months".format(course, duration))

product = "Laptop"
price = 65000

print("Product: {} Price: {}".format(product, price))

city = "Mohali"

print("Training Location: {}".format(city))


# ============================================================
# F-STRINGS
# ============================================================

name = "Aman"
age = 24

print(f"My name is {name} and I am {age} years old")

marks = 95

print(f"Student scored {marks} marks")

product = "Laptop"
price = 65000

print(f"{product} costs Rs. {price}")

model = "CNN"
accuracy = 98.7

print(f"Model: {model} Accuracy: {accuracy}%")

balance = 25000

print(f"Available Balance: Rs. {balance}")


# ============================================================
# ESCAPE SEQUENCES
# ============================================================

# New Line

print("Welcome\nTo\nPython")

# Tab Space

print("Python\tProgramming")

# Single Quote

print('It\'s a Python Workshop')

# Double Quote

print("He said \"Hello\"")

# Backslash

print("C:\\Users\\Student")

# Multiple Lines

print("Name\tMarks")
print("Rahul\t95")
print("Aman\t92")

# Banking Example

print("Account Holder:\tRohit")

# E-Commerce Example

print("Product:\tLaptop")


# ============================================================
# STRING IMMUTABILITY
# ============================================================

# Strings cannot be modified after creation.

language = "Python"

# This will generate an error

# language[0] = "J"

# TypeError:
# 'str' object does not support item assignment

print(language)

# Correct Approach

language = "Jython"

print(language)

# Example

name = "Rahul"

new_name = "A" + name[1:]

print(new_name)

# Replace Method Creates New String

text = "Python"

updated_text = text.replace("P", "J")

print(text)

print(updated_text)

# Verify Different Memory Locations

original = "Python"

modified = original.replace("P", "J")

print(id(original))
print(id(modified))


# ============================================================
# PRACTICE QUESTIONS
# ============================================================

# Question 1
# Print your full name using a string.

# Question 2
# Print the first and last character of your name.

# Question 3
# Reverse the string "Programming".

# Question 4
# Convert "python programming" to uppercase.

# Question 5
# Count the number of characters in your name.

# Question 6
# Replace "Java" with "Python" in a sentence.

# Question 7
# Create a formatted string showing student details.

# Question 8
# Use an f-string to display product information.

# Question 9
# Print a table using tab escape sequence.

# Question 10
# Demonstrate string immutability using an example.

# ============================================================
# PRACTICE QUESTIONS
# ============================================================

# Question 1
# Print your full name using a string.

name="simran chhabra"
print(name)

# Question 2
# Print the first and last character of your name.
print(name[0])
print(name[-1])

# Question 3
# Reverse the string "Programming".
ab="programming"
print(ab[::-1])


# Question 4
# Convert "python programming" to uppercase.
abc="python programming"
print(abc.upper())

# Question 5
# Count the number of characters in your name.
print(len(name))

# Question 6
# Replace "Java" with "Python" in a sentence.
sentence="i like java "
print(sentence.replace("java","python"))

# Question 7
# Create a formatted string showing student details.
student_name="simran"
age=21
print("my name is {name} and age is {age}".format(name=student_name,age=age))

# Question 8
# Use an f-string to display product information.
product_name="laptop"
price=65000
print(f"the product name is {product_name} and its price is {price}")

# Question 9
# Print a table using tab escape sequence.

print("Name\tRoll no\tMarks")
print("simran\t12\t92")
print("jasmine\t17\t98")
print("hitashi\t34\t76")

# Question 10
# Demonstrate string immutability using an example.

# Question 10
# Demonstrate string immutability using an example.
name="simran"
name[0]="j"
print(name)

"""#**Module 8: Lists**"""

# ============================================================
# MODULE 8 : LISTS
# ============================================================

# Lists are ordered, mutable collections that can store
# multiple items of different data types.


# ============================================================
# CREATING LISTS
# ============================================================

# Empty List

numbers = []
print(numbers)

# List of Integers

marks = [85, 90, 78, 92]
print(marks)

# List of Strings

subjects = ["Python", "AI", "ML"]
print(subjects)

# Mixed Data Types

data = ["Rahul", 24, 8.5, True]
print(data)

# Banking Example

transactions = [1000, 2500, 5000]
print(transactions)

# Shopping Example

cart_items = ["Laptop", "Mouse", "Keyboard"]
print(cart_items)

# AI Example

models = ["Linear Regression", "Random Forest", "CNN"]
print(models)


# ============================================================
# LIST INDEXING
# ============================================================

subjects = ["Python", "AI", "ML", "DL"]

print(subjects[0])

print(subjects[1])

print(subjects[2])

print(subjects[-1])

print(subjects[-2])

# Student Example

students = ["Rahul", "Aman", "Riya"]

print(students[0])

print(students[-1])

# Product Example

products = ["Laptop", "Mobile", "Tablet"]

print(products[1])


# ============================================================
# LIST SLICING
# ============================================================

numbers = [10, 20, 30, 40, 50, 60, 70]

print(numbers[0:3])

print(numbers[2:5])

print(numbers[:4])

print(numbers[3:])

print(numbers[-3:])

print(numbers[::2])

print(numbers[::-1])

# Student Example

students = ["Rahul", "Aman", "Riya", "Rohit", "Priya"]

print(students[1:4])


# ============================================================
# LIST METHODS
# ============================================================

# append()

subjects = ["Python", "AI"]

subjects.append("ML")

print(subjects)

# insert()

subjects.insert(1, "Data Science")

print(subjects)

# remove()

subjects.remove("AI")

print(subjects)

# pop()

subjects.pop()

print(subjects)

# extend()

subjects.extend(["Java", "C++"])

print(subjects)

# sort()

marks = [90, 75, 88, 60]

marks.sort()

print(marks)

# reverse()

marks.reverse()

print(marks)

# count()

numbers = [10, 20, 10, 30, 10]

print(numbers.count(10))

# index()

print(numbers.index(20))

# clear()

temp = [1, 2, 3]

temp.clear()

print(temp)


# ============================================================
# NESTED LISTS
# ============================================================

students = [
    ["Rahul", 90],
    ["Aman", 85],
    ["Riya", 95]
]

print(students)

print(students[0])

print(students[0][0])

print(students[0][1])

print(students[2][0])

# Banking Example

accounts = [
    ["Rahul", 25000],
    ["Aman", 50000]
]

print(accounts[1][1])

# AI Example

models = [
    ["CNN", 98.5],
    ["Random Forest", 95.2]
]

print(models[0][0])


# ============================================================
# LIST COMPREHENSION
# ============================================================

# Squares

squares = [x ** 2 for x in range(1, 6)]

print(squares)

# Even Numbers

even_numbers = [x for x in range(1, 21) if x % 2 == 0]

print(even_numbers)

# Odd Numbers

odd_numbers = [x for x in range(1, 21) if x % 2 != 0]

print(odd_numbers)

# Student Roll Numbers

roll_numbers = [x for x in range(1, 11)]

print(roll_numbers)

# Convert Names to Uppercase


names = ["rahul", "aman", "riya"]

upper_names = [name.upper() for name in names]

print(upper_names)

# Length of Strings

courses = ["Python", "Java", "AI"]

lengths = [len(course) for course in courses]

print(lengths)

# Multiples of 5

multiples = [x for x in range(5, 51, 5)]

print(multiples)


# ============================================================
# COPYING LISTS
# ============================================================

# Using copy()

original = [10, 20, 30]
[]
copied = original.copy()

print(original)

print(copied)

# Using list()

subjects = ["Python", "AI", "ML"]

new_subjects = list(subjects)

print(new_subjects)

# Using Slicing

numbers = [1, 2, 3, 4, 5]

copied_numbers = numbers[:]

print(copied_numbers)

# Verify Different Objects

print(id(numbers))

print(id(copied_numbers))

# Modifying Copy

copied_numbers.append(6)

print(numbers)

print(copied_numbers)


# ============================================================
# ITERATING LISTS
# ============================================================

subjects = ["Python", "AI", "ML"]

for subject in subjects:
    print(subject)

# Using Index

for i in range(len(subjects)):
    print(subjects[i])

# Using Enumerate

for index, subject in enumerate(subjects):
    print(index, subject)

# Student Example

students = ["Rahul", "Aman", "Riya"]

for student in students:
    print(student)

# Shopping Example

cart_items = ["Laptop", "Mouse", "Keyboard"]

for item in cart_items:
    print(item)

# Banking Example

transactions = [1000, 2000, 5000]

for amount in transactions:
    print(amount)

# AI Example

models = ["CNN", "RNN", "Transformer"]

for model in models:
    print(model)


# ============================================================
# PRACTICE QUESTIONS
# ============================================================

# Question 1
# Create a list of 5 student names and print it.

# Question 2
# Print the first and last element of a list.

# Question 3
# Reverse a list using slicing.

# Question 4
# Add a new course to a list using append().

# Question 5
# Remove an element from a list using remove().

# Question 6
# Create a nested list of student names and marks.

# Question 7
# Generate squares from 1 to 20 using list comprehension.

# Question 8
# Create a copy of a list and modify the copied version.

# Question 9
# Iterate through a list using enumerate().

# Question 10
# Create a shopping cart list and print all items.

"""#**Module 9: Tuples**"""

# ============================================================
# MODULE 9 : TUPLES
# ============================================================

# Tuples are ordered collections of items.
# Unlike lists, tuples are immutable (cannot be modified).
# Tuples are created using parentheses ().


# ============================================================
# TUPLE BASICS
# ============================================================

# Creating a Tuple

numbers = (10, 20, 30, 40)

print(numbers)

# Tuple with Different Data Types

student = ("Rahul", 21, 8.5, True)

print(student)

# Single Element Tuple

single_value = (100,)

print(single_value)

print(type(single_value))

# Without Parentheses

courses = "Python", "AI", "ML"

print(courses)

# Accessing Elements

subjects = ("Python", "Java", "AI", "ML")

print(subjects[0])

print(subjects[1])

print(subjects[-1])

# Banking Example

account = ("Rahul", 25000)

print(account)

# E-Commerce Example

product = ("Laptop", 65000)

print(product)

# AI Example

model = ("Random Forest", 96.5)

print(model)


# ============================================================
# TUPLE PACKING
# ============================================================

# Packing means storing multiple values into a tuple.

student = ("Rahul", 21, "CSE")

print(student)

# Parentheses are optional

employee = "Aman", 50000, "Developer"

print(employee)

# Banking Example

account_details = "Rohit", 35000, "Savings"

print(account_details)

# Product Example

product_details = "Laptop", 65000, "Electronics"

print(product_details)

# AI Example

model_info = "CNN", 98.7, "Image Classification"

print(model_info)

# Weather Example

weather_data = "Mohali", 35, "Sunny"

print(weather_data)


# ============================================================
# TUPLE UNPACKING
# ============================================================

# Unpacking means extracting tuple values into variables.

student = ("Rahul", 22, "CSE")

name, age, branch = student

print(name)
print(age)
print(branch)

# Employee Example

employee = ("Aman", 50000)

employee_name, salary = employee

print(employee_name)
print(salary)

# Banking Example

account = ("Rohit", 25000)

holder, balance = account

print(holder)
print(balance)

# Product Example

product = ("Laptop", 65000)

product_name, product_price = product

print(product_name)
print(product_price)

# AI Example

model = ("CNN", 98.5)

model_name, accuracy = model

print(model_name)
print(accuracy)

# Multiple Values

x, y, z = (10, 20, 30)

print(x)
print(y)
print(z)


# ============================================================
# TUPLE METHODS
# ============================================================

# Tuples have only two built-in methods:
# count() and index()

numbers = (10, 20, 30, 10, 40, 10)

# count()

print(numbers.count(10))

print(numbers.count(20))

# index()

print(numbers.index(30))

print(numbers.index(40))

# Student Example

marks = (85, 90, 85, 95, 85)

print(marks.count(85))

print(marks.index(90))

# Product Example

products = ("Laptop", "Mouse", "Keyboard")

print(products.index("Mouse"))

# AI Example

models = ("CNN", "RNN", "Transformer")

print(models.index("RNN"))


# ============================================================
# IMMUTABLE NATURE
# ============================================================

# Tuples cannot be modified after creation.

numbers = (10, 20, 30)

print(numbers)

# The following statement will generate an error.

# numbers[0] = 100

# TypeError:
# 'tuple' object does not support item assignment


# Creating a New Tuple Instead

numbers = (100, 20, 30)

print(numbers)

# String Inside Tuple

student = ("Rahul", "CSE")

print(student)

# Reassigning Entire Tuple

student = ("Aman", "AI")

print(student)

# Immutable Data Example

account_number = (123456789,)

print(account_number)

# AI Configuration Example

model_config = ("CNN", 128, 0.001)

print(model_config)

# Database Record Example

record = (101, "Rahul", "Python")

print(record)

# Tuple Length

print(len(record))

# Membership Test

print("Rahul" in record)

print("Aman" in record)


# ============================================================
# PRACTICE QUESTIONS
# ============================================================

# Question 1
# Create a tuple containing five numbers.

# Question 2
# Create a tuple containing student information.

# Question 3
# Access the first and last element of a tuple.

# Question 4
# Perform tuple packing using employee details.

# Question 5
# Perform tuple unpacking using product details.

# Question 6
# Count how many times a number appears in a tuple.

# Question 7
# Find the index of a specific element.

# Question 8
# Verify that tuples are immutable.

# Question 9
# Check membership using 'in' operator.

# Question 10
# Create an AI model configuration tuple and display its values.

"""#**Module 10: Sets**"""

# ============================================================
# MODULE 10 : SETS
# ============================================================

# Sets are unordered collections of unique elements.
# Duplicate values are automatically removed.
# Sets are created using curly braces {}.


# ============================================================
# CREATING SETS
# ============================================================

# Integer Set

numbers = {10, 20, 30, 40}

print(numbers)

# String Set

subjects = {"Python", "AI", "ML"}

print(subjects)

# Mixed Data Types

data = {"Rahul", 24, 8.5, True}

print(data)

# Duplicate Values are Removed

marks = {90, 80, 90, 70, 80}

print(marks)

# Empty Set

empty_set = set()

print(empty_set)

# Student Example

students = {"Rahul", "Aman", "Riya"}

print(students)

# Banking Example

account_types = {"Savings", "Current", "Fixed Deposit"}

print(account_types)

# AI Example

models = {"CNN", "RNN", "Transformer"}

print(models)


# ============================================================
# SET METHODS
# ============================================================

subjects = {"Python", "AI"}

print(subjects)

# add()

subjects.add("ML")

print(subjects)

# update()

subjects.update(["DL", "Data Science"])

print(subjects)

# remove()

subjects.remove("AI")

print(subjects)

# discard()

subjects.discard("Java")

print(subjects)

# pop()

removed_item = subjects.pop()

print("Removed:", removed_item)

print(subjects)

# clear()

temp_set = {1, 2, 3}

temp_set.clear()

print(temp_set)

# copy()

original = {"Python", "AI"}

copied = original.copy()

print(copied)


# ============================================================
# SET OPERATIONS
# ============================================================

set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}

print(set1)
print(set2)

# Membership

print(3 in set1)

print(10 in set1)

# Length

print(len(set1))

# Subset

print({1, 2}.issubset(set1))

# Superset

print(set1.issuperset({1, 2}))


# ============================================================
# UNION
# ============================================================

python_students = {"Rahul", "Aman", "Riya"}

ai_students = {"Riya", "Rohit", "Priya"}

all_students = python_students.union(ai_students)

print(all_students)

# Using Operator

print(python_students | ai_students)

# Subject Example

subject1 = {"Python", "Java"}
subject2 = {"AI", "ML"}

print(subject1.union(subject2))


# ============================================================
# INTERSECTION
# ============================================================

python_students = {"Rahul", "Aman", "Riya"}

ai_students = {"Riya", "Rohit", "Priya"}

common_students = python_students.intersection(ai_students)

print(common_students)

# Using Operator

print(python_students & ai_students)

# Product Example

store1 = {"Laptop", "Mouse", "Keyboard"}
store2 = {"Mouse", "Monitor", "Laptop"}

print(store1.intersection(store2))


# ============================================================
# DIFFERENCE
# ============================================================

python_students = {"Rahul", "Aman", "Riya"}

ai_students = {"Riya", "Rohit", "Priya"}

print(python_students.difference(ai_students))

# Using Operator

print(python_students - ai_students)

# Product Example

products_a = {"Laptop", "Mouse", "Keyboard"}
products_b = {"Mouse", "Monitor"}

print(products_a - products_b)


# ============================================================
# SYMMETRIC DIFFERENCE
# ============================================================

python_students = {"Rahul", "Aman", "Riya"}

ai_students = {"Riya", "Rohit", "Priya"}

print(python_students.symmetric_difference(ai_students))

# Using Operator

print(python_students ^ ai_students)

# Product Example

store1 = {"Laptop", "Mouse", "Keyboard"}
store2 = {"Mouse", "Monitor", "Laptop"}

print(store1 ^ store2)


# ============================================================
# FROZEN SETS
# ============================================================

# Frozen sets are immutable versions of sets.

frozen_numbers = frozenset([10, 20, 30, 40])

print(frozen_numbers)

# Membership Check

print(20 in frozen_numbers)

# Length

print(len(frozen_numbers))

# Frozen Set Example

courses = frozenset(["Python", "AI", "ML"])

print(courses)

# Student Example

students = frozenset(["Rahul", "Aman", "Riya"])

print(students)

# Banking Example

account_types = frozenset(["Savings", "Current"])

print(account_types)

# AI Example

models = frozenset(["CNN", "RNN", "Transformer"])

print(models)

# The following statements will generate errors.

# courses.add("DL")
# courses.remove("AI")

# Frozen sets cannot be modified.


# ============================================================
# PRACTICE QUESTIONS
# ============================================================

# Question 1
# Create a set containing five numbers.

# Question 2
# Create a set of student names.

# Question 3
# Add a new subject to a set.

# Question 4
# Remove an element from a set.

# Question 5
# Find the union of two sets.

# Question 6
# Find the intersection of two sets.

# Question 7
# Find the difference between two sets.

# Question 8
# Find the symmetric difference between two sets.

# Question 9
# Create a frozen set and perform membership testing.

# Question 10
# Verify that duplicate values are removed automatically from a set.

"""#**Module 11: Dictionaries**"""

# ============================================================
# MODULE 11 : DICTIONARIES
# ============================================================

# Dictionaries store data in key-value pairs.
# Dictionaries are mutable, ordered, and use curly braces {}.


# ============================================================
# CREATING DICTIONARIES
# ============================================================

# Student Dictionary

student = {
    "name": "Rahul",
    "age": 21,
    "course": "Python"
}

print(student)

# Banking Dictionary

account = {
    "account_holder": "Aman",
    "balance": 50000
}

print(account)

# Product Dictionary

product = {
    "name": "Laptop",
    "price": 65000
}

print(product)

# AI Model Dictionary

model = {
    "model_name": "Random Forest",
    "accuracy": 96.5
}

print(model)

# Empty Dictionary

empty_dict = {}

print(empty_dict)

# Using dict() Constructor

employee = dict(
    name="Rohit",
    salary=45000
)

print(employee)

# Mixed Data Types

data = {
    "name": "Priya",
    "age": 25,
    "cgpa": 8.8,
    "placed": True
}

print(data)


# ============================================================
# ACCESSING DICTIONARY ELEMENTS
# ============================================================

student = {
    "name": "Rahul",
    "age": 21,
    "course": "Python"
}

print(student["name"])

print(student["age"])

print(student["course"])

# Using get()

print(student.get("name"))

print(student.get("age"))

# Avoids Error if Key Does Not Exist

print(student.get("salary"))

# Banking Example

account = {
    "holder": "Aman",
    "balance": 25000
}

print(account["holder"])

print(account["balance"])

# Product Example

product = {
    "name": "Laptop",
    "price": 65000
}

print(product["name"])


# ============================================================
# DICTIONARY METHODS
# ============================================================

student = {
    "name": "Rahul",
    "age": 21
}

print(student)

# keys()

print(student.keys())

# values()

print(student.values())

# items()

print(student.items())

# update()

student.update({"course": "Python"})

print(student)

# pop()

student.pop("age")

print(student)

# copy()

new_student = student.copy()

print(new_student)

# setdefault()

student.setdefault("city", "Mohali")

print(student)

# clear()

temp = {
    "a": 1,
    "b": 2
}

temp.clear()

print(temp)


# ============================================================
# NESTED DICTIONARIES
# ============================================================

students = {
    "student1": {
        "name": "Rahul",
        "marks": 90
    },
    "student2": {
        "name": "Aman",
        "marks": 85
    }
}

print(students)

print(students["student1"])

print(students["student1"]["name"])

print(students["student2"]["marks"])

# Banking Example

accounts = {
    "acc1": {
        "holder": "Rahul",
        "balance": 50000
    },
    "acc2": {
        "holder": "Aman",
        "balance": 25000
    }
}

print(accounts["acc1"]["holder"])

print(accounts["acc2"]["balance"])

# AI Example

models = {
    "model1": {
        "name": "CNN",
        "accuracy": 98.5
    }
}

print(models["model1"]["name"])


# ============================================================
# DICTIONARY COMPREHENSION
# ============================================================

# Squares of Numbers

squares = {x: x ** 2 for x in range(1, 6)}

print(squares)

# Even Numbers

even_numbers = {
    x: x * 10
    for x in range(1, 11)
    if x % 2 == 0
}

print(even_numbers)

# Student Roll Numbers

students = {
    roll: f"Student_{roll}"
    for roll in range(1, 6)
}

print(students)

# Course Dictionary

courses = {
    course: len(course)
    for course in ["Python", "AI", "ML"]
}

print(courses)

# Product Prices

products = {
    "Laptop": 65000,
    "Mouse": 500,
    "Keyboard": 1500
}

discounted_prices = {
    key: value * 0.9
    for key, value in products.items()
}

print(discounted_prices)

# AI Example

models = {
    "CNN": 98,
    "RNN": 95,
    "Transformer": 99
}

improved_models = {
    model: accuracy + 1
    for model, accuracy in models.items()
}

print(improved_models)


# ============================================================
# ITERATING DICTIONARIES
# ============================================================

student = {
    "name": "Rahul",
    "age": 21,
    "course": "Python"
}

# Iterate Through Keys

for key in student:
    print(key)

# Iterate Through Values

for value in student.values():
    print(value)

# Iterate Through Key-Value Pairs

for key, value in student.items():
    print(key, ":", value)

# Banking Example

account = {
    "holder": "Aman",
    "balance": 25000
}

for key, value in account.items():
    print(key, ":", value)

# Product Example

product = {
    "name": "Laptop",
    "price": 65000
}

for key, value in product.items():
    print(key, ":", value)

# AI Example

model = {
    "name": "CNN",
    "accuracy": 98.5
}

for key, value in model.items():
    print(key, ":", value)


# ============================================================
# PRACTICE QUESTIONS
# ============================================================

# Question 1
# Create a dictionary containing student information.

# Question 2
# Access and print a specific key from a dictionary.

# Question 3
# Add a new key-value pair using update().

# Question 4
# Display all keys of a dictionary.

# Question 5
# Display all values of a dictionary.

# Question 6
# Create a nested dictionary for two students.

# Question 7
# Generate a dictionary of squares using comprehension.

# Question 8
# Iterate through a dictionary and print key-value pairs.

# Question 9
# Create a banking dictionary and display account details.

# Question 10
# Create an AI model dictionary and iterate through it.

"""#**Module 12: Advanced Data Structures**"""

# ============================================================
# MODULE 12 : ADVANCED DATA STRUCTURES
# ============================================================

# Python provides several built-in and specialized data
# structures for efficient data storage and manipulation.

# In this module, we will cover:
# 1. Arrays
# 2. Stack
# 3. Queue
# 4. Deque
# 5. Heap Basics


# ============================================================
# ARRAYS
# ============================================================

# Arrays store elements of the same data type.

from array import array

numbers = array('i', [10, 20, 30, 40, 50])

print(numbers)

# Access Elements

print(numbers[0])
print(numbers[2])

# Add Element

numbers.append(60)

print(numbers)

# Insert Element

numbers.insert(1, 15)

print(numbers)

# Remove Element

numbers.remove(30)

print(numbers)

# Iterate Through Array

for number in numbers:
    print(number)

# Student Marks Example

marks = array('i', [85, 90, 78, 92])

for mark in marks:
    print(mark)

# Banking Example

transactions = array('i', [1000, 2500, 5000])

print(transactions)

# AI Example

epochs = array('i', [10, 20, 30])

print(epochs)


# ============================================================
# STACK
# ============================================================

# Stack follows LIFO
# Last In First Out

stack = []

# Push Operation

stack.append("Python")
stack.append("AI")
stack.append("ML")

print(stack)

# Pop Operation

removed_item = stack.pop()

print("Removed:", removed_item)

print(stack)

# Peek Operation

print("Top Element:", stack[-1])

# Check Stack Size

print("Size:", len(stack))

# Browser History Example

history = []

history.append("Google")
history.append("YouTube")
history.append("ChatGPT")

print(history)

history.pop()

print(history)

# Book Stack Example

books = []

books.append("Book 1")
books.append("Book 2")
books.append("Book 3")

print(books)


# ============================================================
# QUEUE
# ============================================================

# Queue follows FIFO
# First In First Out

from collections import deque

queue = deque()

# Enqueue

queue.append("Customer 1")
queue.append("Customer 2")
queue.append("Customer 3")

print(queue)

# Dequeue

served_customer = queue.popleft()

print("Served:", served_customer)

print(queue)

# Queue Size

print(len(queue))

# Ticket Counter Example

tickets = deque()

tickets.append("Person A")
tickets.append("Person B")
tickets.append("Person C")

print(tickets)

tickets.popleft()

print(tickets)

# Print Queue

documents = deque()

documents.append("Doc1")
documents.append("Doc2")
documents.append("Doc3")

print(documents)


# ============================================================
# DEQUE
# ============================================================

# Deque stands for Double Ended Queue.
# Elements can be added or removed from both ends.

from collections import deque

dq = deque()

# Insert at Right

dq.append(10)
dq.append(20)

print(dq)

# Insert at Left

dq.appendleft(5)

print(dq)

# Remove from Right

dq.pop()

print(dq)

# Remove from Left

dq.popleft()

print(dq)

# Student Line Example

students = deque()

students.append("Rahul")
students.append("Aman")

students.appendleft("Monitor")

print(students)

# Undo Feature Example

actions = deque(["Open", "Edit", "Save"])

print(actions)


# ============================================================
# HEAP BASICS
# ============================================================

# Heap is a specialized tree-based data structure.
# Python provides min-heap using heapq module.

import heapq

numbers = [30, 10, 50, 20, 40]

heapq.heapify(numbers)

print(numbers)

# Smallest Element

print(heapq.heappop(numbers))

print(numbers)

# Insert Element

heapq.heappush(numbers, 5)

print(numbers)

# Peek Minimum Element

print(numbers[0])

# Student Marks Example

marks = [90, 70, 85, 60, 95]

heapq.heapify(marks)

print(marks)

print(heapq.heappop(marks))

# Banking Example

transactions = [5000, 1000, 7000, 2000]

heapq.heapify(transactions)

print(transactions)

# AI Example

loss_values = [0.45, 0.30, 0.55, 0.20]

heapq.heapify(loss_values)

print(loss_values)

print(heapq.heappop(loss_values))


# ============================================================
# PRACTICE QUESTIONS
# ============================================================

# Question 1
# Create an array of 5 numbers and print all elements.

# Question 2
# Add a new element to an array.

# Question 3
# Implement a stack and perform push/pop operations.

# Question 4
# Create a browser history using stack.

# Question 5
# Implement a queue for customer service.

# Question 6
# Remove an element from a queue using popleft().

# Question 7
# Create a deque and add elements from both ends.

# Question 8
# Remove elements from both ends of a deque.

# Question 9
# Create a min-heap using heapq.

# Question 10
# Find the smallest element from a heap.